### ISSUE TITLE
Missing Buffer Button

### ISSUE THREAD

**Issue by Nidre** [bufferapp/buffer-firefox#13] opened 2015-07-18 18:47 UTC
Buffer button is removed each time Firefox is restarted. This issue currently occurs on Nightly x64 Build 42.0a1 (2015-07-17) with E10's and Buffer 2.12.3.

This is the error that I've got in browser console: 
http://pastebin.com/2ccRACNF

I've  also updated the topic at Bugzilla if that helps: https://bugzilla.mozilla.org/show_bug.cgi?id=1059855

**Comment by thepelkus** [comment] 2015-07-20 00:58
Hello there!

I took a look at this issue with 42.0a1 (2015-07-19), and while I could reproduce the issue from an end user perspective, I was getting a different stack trace: http://pastebin.com/83gkxpqz

Based on this, it appears that the exception is rooted in the require of the selection API in main.js. I tested this by removing the require and using an arbitrary string in the Pablo context menu URL. The result was that the plugin icon would appear as expected on application start. I've been unable to discover a solution to this problem so far that would preserve the Pablo menu item functionality, but hopefully this data will prove useful to you!

PS: From a Buffer user (me)—thanks for the great work, y'all!

**Comment by djfarrelly** [comment] 2015-07-28 15:40
Thanks so much for reporting and looking into this stuff, it looks like the issues with the selection API is still happening after we've brought it back. Hoping to fix this soon!

**Comment by philippe-git** [comment] 2017-01-25 15:10
You've probably seen this in the [Bugzilla thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1059855): this issue is now fixed after migrating to the WebExtensions API. The AMO version will be published as soon as it's reviewed, and our self-hosted version is already up to date: https://buffer.com/extensions

Thanks a lot for your help, here and in that Bugzilla thread!

**Closed by philippe-git** 2017-01-25 15:10 UTC
Labels: bug
